[build]
builder = "nixpacks"
installCommand = "npm install"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
